DELETE http://localhost:1337/list/ead749ef-7797-11ec-9a80-74d02b05f0ad HTTP/1.1
content-type: application/json

###
PUT http://localhost:1337/list/65ab8473-7798-11ec-9a80-74d02b05f0ad HTTP/1.1
content-type: application/json

{
    "newName":"It happeneeeeeeeeeeeeeeeeeddddddddddddd"
}
###
GET http://localhost:1337/list HTTP/1.1
content-type: application/json
